apiVersion: v1
kind: Pod

metadata:
  name: python-sidecar-demo

spec:
  containers:

    # Main Container
    - name: nginx
      image: nginx

      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

    # Sidecar Container
    - name: python-sidecar
      image: python:3.12-slim

      command:
        - python
        - -c
        - |
          import time

          while True:
              with open("/data/index.html", "w") as f:
                  f.write("<h1>Hello from Python Sidecar</h1>")

              print("File Updated")
              time.sleep(5)

      volumeMounts:
        - name: shared-data
          mountPath: /data

  volumes:
    - name: shared-data
      emptyDir: {}
